# Generated by Django 5.2.8 on 2026-09-09 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_created_by_alter_contract_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clause',
            options={'ordering': ['order_number']},
        ),
        migrations.RemoveField(
            model_name='modification',
            name='new_text',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='old_text',
        ),
        migrations.AddField(
            model_name='clause',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clause',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='modification',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='modification',
            name='original_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='proposed_modification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='clause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications', to='contracts.clause'),
        ),
    ]
